language: android

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager), install the system image, and create and start emulator.
  - sdkmanager tools && \
    sdkmanager "system-images;android-18;default;armeabi-v7a" && \
    echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a" && \
    $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install: ./gradlew build assembleAndroidTest --stacktrace

before_script:
  # Foreground the emulator installation, creation, and starting and ensure it completes.
  - fg
  # Wait for the emulator to fully boot.
  - android-wait-for-emulator
  # Dismiss the lock screen (if any) on the emulator.
  - adb shell input keyevent 82

script:
  - ./gradlew connectedCheck --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "kgsT0j2b0GYbQjrDSdIYoh9lXOb2bAqA8gOx7ipegYLiNUuAjTeclw/3IFd5WpPNEhwTvDlb8Pwi/GYsXwYLdjysZUsj73a027swKAuXRBEjnBpfcvhEwKdoO5Ygoz/uH7TvcuCKzEz/bRKIglvn9PcTrzIHHZZIXa/mLU5otNE="
    - secure: "XNvNiKfh2+JAHvbj7/jtaHKcu5FlN0fHwKwiDZYiCkTkG4kXsKlGtbQX4uk/RU4ZEe3pCPt1I6u66e5c57SLiDNMI0dnjdmSWL6Pcd1CoJVagYYq48TNgQARRe1zntXZvweRmqbfnsQiX5neLwaDj+UNM1yq6D3h2quPVrgoBBM="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
